{"uuid": "8a04e519-81ce-4183-b35b-7d0dac99ae1d", "children": ["d6347173-2843-4225-be6e-f627bc891878"], "befores": [{"name": "function_fixture2", "status": "passed", "start": 1705657020870, "stop": 1705657024682}], "afters": [{"name": "function_fixture2::driver_teardown", "status": "broken", "statusDetails": {"message": "AttributeError: 'WebDriver' object has no attribute 'close_app'\n", "trace": "  File \"/Users/hpc/pytest/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/hpc/pytest/conftest.py\", line 25, in driver_teardown\n    request.instance.driver.close_app()\n"}, "start": 1705657037944, "stop": 1705657037945}], "start": 1705657020870, "stop": 1705657037945}