{"uuid": "93556182-2cdf-41b2-ad0f-99bc3cab11ad", "children": ["2bdb10bb-a597-4297-9d32-a391d2f67354"], "befores": [{"name": "function_fixture2", "status": "passed", "start": 1705654052628, "stop": 1705654052684}], "afters": [{"name": "function_fixture2::driver_teardown", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'close_app'\n", "trace": "  File \"/Users/hpc/pytest/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/hpc/pytest/conftest.py\", line 25, in driver_teardown\n    request.instance.driver.close_app()\n"}, "start": 1705654052707, "stop": 1705654052708}], "start": 1705654052628, "stop": 1705654052708}