{"uuid": "166c2dd1-6726-4158-8b79-1118426e285d", "children": ["1b857caa-0b66-4c24-b17a-38dddb3e283b"], "befores": [{"name": "function_fixture2", "status": "passed", "start": 1705657441031, "stop": 1705657448938}], "afters": [{"name": "function_fixture2::driver_teardown", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'close_app'\n", "trace": "  File \"/Users/hpc/pytest/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/hpc/pytest/conftest.py\", line 25, in driver_teardown\n    request.instance.driver.close_app()\n"}, "start": 1705657448982, "stop": 1705657448983}], "start": 1705657441031, "stop": 1705657448983}