{"uuid": "7c200756-f073-43cc-b688-c0d3bb5e5b5b", "children": ["0f30d94a-37e6-49b2-9d3d-6cb57f56332d"], "befores": [{"name": "function_fixture2", "status": "passed", "start": 1705653315365, "stop": 1705653319386}], "afters": [{"name": "function_fixture2::driver_teardown", "status": "broken", "statusDetails": {"message": "AttributeError: 'WebDriver' object has no attribute 'close_app'\n", "trace": "  File \"/Users/hpc/pytest/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/hpc/pytest/conftest.py\", line 25, in driver_teardown\n    request.instance.driver.close_app()\n"}, "start": 1705653341299, "stop": 1705653341300}], "start": 1705653315365, "stop": 1705653341300}